#!/bin/bash
set -e

# Add setup for API lab
echo "Setup for the API lab..."
echo "Static App URL : $STATIC_APP"
echo "Dynamic App URL: $DYNAMIC_APP"

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid

exec apache2ctl -DFOREGROUND