version: "3.9"
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  web:
    build: ./docker-images/apache-php-image
    image: api/php-server
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`demo.api.ch`)
      - traefik.http.services.web.loadbalancer.server.port=80
      - traefik.http.services.web.loadbalancer.sticky.cookie=true

  api: 
    build: ./docker-images/express-image
    image: api/express-server
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=(Host(`demo.api.ch`) && Path(`/api/random`))
      - traefik.http.services.api.loadbalancer.server.port=3000
      - traefik.http.routers.api.middlewares=stripprefix
      - traefik.http.middlewares.stripprefix.stripprefix.prefixes=/api/random

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9000:9000